version: "3.4"

services:
    botuser:
        image: bot
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
